language: php

php:
- 7.1

sudo: false

cache:
  directories:
  - "$HOME/.composer/cache"

matrix:
  include:
  - php: 7.1
    env:
    - EXECUTE_DEPLOYMENT=true

before_install:
- openssl aes-256-cbc -K $encrypted_3fa200ce5c41_key -iv $encrypted_3fa200ce5c41_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d

before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist
- composer info -i

script:
- vendor/bin/phpcs --standard=psr2 src/
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
- |
  if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  fi

after_success:
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev ; fi
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./bin/deploy.sh ; fi

notifications:
  email: false
  irc: "irc.freenode.org#polderknowledge"
